### ISSUE TITLE
installation for nvcr images

### ISSUE THREAD

**Issue by ftgreat** [Dao-AILab/causal-conv1d#10]
I use the nvcr base image: nvcr.io/nvidia/pytorch:23.06-py3.

Pip install directly failed as follows. 
![image](https://github.com/Dao-AILab/causal-conv1d/assets/10432020/5b712a0c-4a4a-4f6d-ac0b-e9f0a4dafd3c)

Should I install from sources and how to set these variables below in setup.py for nvcr base image? 

![image](https://github.com/Dao-AILab/causal-conv1d/assets/10432020/578479d8-632c-4039-8ad5-b729b9cabcbc)

Thanks for your advice.

**Comment by tridao** [comment]
nvcr uses pytorch nightly versions so it's a bit hard to make sure the compiled CUDA wheels are compatible. causal-conv v1.1.1 should work with nvcr 23.12.

**Comment by ftgreat** [comment]
thanks.
installed succefully from source build with force build.
