### ISSUE TITLE
Comparison between Casual-Conv1d_Cuda and F.conv1d

### ISSUE THREAD

**Issue by ZetangForward** [Dao-AILab/causal-conv1d#19]
Hi, I wonder how much faster can it be compared to using the built-in F.conv1d in pytorch after adding Casual-Conv1d_Cuda? 
Because I want to try a larger convolution kernel, but causal_conv1d_fn doesn't seem to support it (it can only support up to 4 at most)

**Comment by tridao** [comment]
You can benchmark it, it's as fast as a memcpy (i.e. as fast as `torch.clone(input)`). The constraint is that it only works for kernel size 2, 3, 4.

**Comment by ZetangForward** [comment]
> You can benchmark it, it's as fast as a memcpy (i.e. as fast as `torch.clone(input)`). The constraint is that it only works for kernel size 2, 3, 4.

ok， thanks， I will test it.
