### ISSUE TITLE
are there any version for ARM platform like Jetson?

### ISSUE THREAD

**Issue by zuoweic** [Dao-AILab/causal-conv1d#28]
I wanna deploy the vision mamba on my jetson AGX  Orin, which is of ARM, but i didn't find any wheel for arm,  all of them are for X86-64, so is it possible for me to use this package on my jetson agx platform?

**Comment by tridao** [comment]
I think so, you just have to compile it from source.

**Comment by zuoweic** [comment]
yeah it works thank u so much for your reply!
